name: Build PyInstaller Executables

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
        python-version: [3.11]        
    
    runs-on: ${{ matrix.os }}
    
    steps:
    # Checkout repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    # Install dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Build executable
    - name: Build Executable
      run: |
        cd app
        pyinstaller --name crossword-creator-${{ matrix.os }} --windowed --onefile --add-data "static:static" serve_with_gui.py

    # Upload artifacts
    - name: Upload Executable
      uses: actions/upload-artifact@v2
      with:
        name: crossword-creator-${{ matrix.os }}
        path: app/dist/crossword-creator-${{ matrix.os }}*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.0
        release_name: v1.0.0
        draft: false
        prerelease: false

    - name: Upload Release Asset (Ubuntu 22.04)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: app/dist/crossword-creator-ubuntu-22.04
        asset_name: crossword-creator-ubuntu-22.04
        asset_content_type: application/octet-stream

    - name: Upload Release Asset (Ubuntu 24.04)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: app/dist/crossword-creator-ubuntu-24.04
        asset_name: crossword-creator-ubuntu-24.04
        asset_content_type: application/octet-stream